# Generated by Django 2.1.7 on 2019-05-19 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_merge_20190214_1427'),
        ('leads', '0008_auto_20190315_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='contacts',
        ),
        migrations.AddField(
            model_name='lead',
            name='contacts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lead_contacts', to='contacts.Contact'),
            preserve_default=False,
        ),
    ]
