# Generated by Django 2.1.7 on 2019-05-20 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20190520_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contacts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_contacts', to='contacts.Contact'),
        ),
    ]
