# Generated by Django 2.1.7 on 2019-05-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20190521_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Title'),
        ),
    ]
