# Generated by Django 2.1.7 on 2019-05-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='contacts',
        ),
    ]
